name: Code Scanning
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: pip install --upgrade pip
    - run: pip install requirements.txt
    - run: pip install "black<23" pylint==v3.0.0a3 mypy==v0.902
    - run: black --check .
    - run: pylint --errors-only ./src/*
    - run: mypy --strict .